### ISSUE TITLE
Use same service definition

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/template-service-go#3]
Change the service definition to the same as other templates:
https://github.com/mesg-foundation/template-service-typescript/blob/master/template/mesg.yml
https://github.com/mesg-foundation/template-service-javascript/blob/master/template/mesg.yml
https://github.com/mesg-foundation/template-service-basic/blob/master/template/mesg.yml

```yaml

name: myservice
sid: myservice
description: "Description of my service"
tasks:
  taskX:
    inputs:
      foo:
        type: String
      bar:
        type: String
    outputs:
      message:
        type: String
events:
  started:
    data:
      x:
        type: Boolean
```
